version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: airflow_db
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: airflow_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  airflow-init:
    build: .
    container_name: airflow_init
    depends_on:
      - mysql
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init &&
      airflow users create
        --username admin
        --firstname admin
        --lastname admin
        --role Admin
        --email admin@example.com
        --password admin
      "

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      - mysql
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      DBT_PROFILES_DIR: /opt/airflow/dbt/github_event_analysis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
      - "8081:8081"
    command: webserver

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      - mysql
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      DBT_PROFILES_DIR: /opt/airflow/dbt/github_event_analysis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    command: scheduler

volumes:
  mysql_data:
