version: '3.8'
 
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: airflow_db
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: airflow_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "airflow_user", "-pairflow_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
 
  airflow-init:
    build: .
    container_name: airflow_init
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DWH_DATABASE: github_event_analysis
      MYSQL_DWH_USER: samboy_88
      MYSQL_DWH_PASSWORD: awesome_person
    volumes:
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh"]
 
  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      mysql:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      DBT_PROFILES_DIR: /opt/airflow/dbt/github_event_analysis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
      - "8081:8081"
    command: webserver
 
  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      mysql:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://airflow_user:airflow_password@mysql:3306/airflow_db
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_123"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      DBT_PROFILES_DIR: /opt/airflow/dbt/github_event_analysis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    command: scheduler
 
volumes:
  mysql_data: